version: '3.9'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: obrato
      POSTGRES_PASSWORD: obrato
      POSTGRES_DB: obrato
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U obrato']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:RELEASE.2024-02-06T21-36-22Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000'
      - '9001:9001'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    volumes:
      - es_data:/usr/share/elasticsearch/data

  api:
    build:
      context: ..
      dockerfile: apps/api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      elasticsearch:
        condition: service_started
      minio:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://obrato:obrato@postgres:5432/obrato
      REDIS_HOST: redis
      REDIS_PORT: 6379
      ELASTICSEARCH_NODE: http://elasticsearch:9200
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin
      S3_BUCKET: obrato-files
      JWT_SECRET: local-secret
      JWT_REFRESH_SECRET: local-refresh
      PORT: 3000
    ports:
      - '3000:3000'

  web:
    build:
      context: ..
      dockerfile: apps/web/Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
      API_INTERNAL_URL: http://api:3000
    depends_on:
      api:
        condition: service_started
    ports:
      - '3001:3000'

volumes:
  postgres_data:
  redis_data:
  minio_data:
  es_data:
